#pragma once

enum Pins
{
    TX_PIN,
    RX_PIN,
    BUZZER1_PIN,
    BUZZER2_PIN,
    GPIO_4_PIN,
    EXTERNAL_LED_IN_PIN,
    GPIO_6_PIN,
    GPIO_7_PIN,
    BT_UART_TX_PIN,
    BT_UART_RX_PIN,
    BT_UART_CTS_PIN,
    BT_UART_RTS_PIN,
    BT_IO1_PIN,
    BT_IO2_PIN,
    BT_RESET_PIN,
    GPIO_15_PIN,
    SDA_MOSI_PIN,
    SCL_SCLK_PIN,
    NOT_CONNECTED,
    SW1_PIN,
    SW2_PIN,
    SW3_PIN,
    ON_BOARD_SW_PIN,
    MOTOR_PWR_CTRL_PIN,
    MOTOR_FAULT_FLAG_PIN,
    MOTOR_IN_PIN,
    GPIO_26_PIN,
    GPIO_27_PIN,
    VIBRATION_OUTPUT1_PIN,
    VIBRATION_OUTPUT2_PIN
};

enum Mode
{
    DEFAULT_MODE,
    PIEZO_TEST_MODE,
    DISPLAY_TEST_MODE,
    BLUETOOTH_TEST_MODE,
    MOTOR_TEST_MODE,
    NUM_MODES
};

enum State
{
    SETUP,
    SERVE_DETECTION,
    BOUNCE_LISTEN,
    CAMERA_CHECK,
    POINT_ADD,
    VICTORY,
    FOUL  
};

enum Player
{
    PLAYER_1,
    PLAYER_2
};
